WARNING    - 2024-06-14 21:42:05,660 - bot             : Privileged message content intent is missing, commands may not work as expected.
INFO       - 2024-06-14 21:42:05,660 - client          : logging in using static token
INFO       - 2024-06-14 21:42:07,263 - gateway         : Shard ID None has connected to Gateway (Session ID: de76831537ca688fed44346f0780e41c).
ERROR      - 2024-06-14 21:42:09,468 - client          : Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 947, in _load_from_module_spec
    await setup(self)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "J:\Belajar\discord-bot-py\main.py", line 95, in on_ready
    await bot.load_extension(f"cogs.{cog_file.name[:-3]}")
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1013, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\LAB SISTER\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 952, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.help' raised an error: TypeError: object NoneType can't be used in 'await' expression
